### ISSUE TITLE
Clean the data

### ISSUE THREAD

**Issue by cl0ckwork** [cl0ckwork/dw-timescale-db#7]
We need someone to clean the data and turn it into something more useful. specifically the `sentiment` column
`Sentiment(polarity=0.0, subjectivity=0.0)`
will not really cut it when making graphs.
we should probably create two columns from this:
`polarity` and `subjectivity`

additionally @iamdeepaka did the `created_at` parse correctly?

**Comment by cl0ckwork** [comment]
the `created_at ` column is not in timestamp format.. it needs to be parsed into something SQL can understand, or a format needs to be provided to SQL. my suggestion would be the later

format: `YYYY-MM-DDTHH:MM:SSZ`

this is the current error causing this problem:
`2:8: conversion failed: "Thu Nov 01 04:20:04 +0000 2018" to timestamp`

**Comment by jfogerty18** [comment]
I can try and resolve this

**Comment by jfogerty18** [comment]
do you want date time as index?

**Comment by jfogerty18** [comment]
I have uploaded the file and shared through google drive.
