### ISSUE TITLE
Research the database characteristics

### ISSUE THREAD

**Issue by cl0ckwork** [cl0ckwork/dw-timescale-db#8]
I imagine multiple people will address this issue, Id recommend claiming a few of the below, researching them, and making a slide or two about your findings.

From the requirements:

- specific characteristics, 
- key features,
- similarities and differences with the other NoSQL databases, 
- consistency concepts, 
- transaction concepts, 
- partitioning methods, 
- competitive advantages, 
- key customers, 
- market metrics, 
- licensing,
-  pricing models, 
- drawbacks, etc.

adding this for reference:

Prepare a presentation containing findings about the system including a demo (25-30 minutes including discussion). The demo part of the presentation should take no less than 10 minutes.

**Comment by jfogerty18** [comment]
We did all bullet points except market metrics and similarities.

**Comment by cl0ckwork** [comment]
@jfogerty18 instead of similarities, which seem to be addressed in the two slides about PostGres I added alternatives which address the other choices int he NoSQL world

**Comment by cl0ckwork** [comment]
@jfogerty18 @jiarongche You both did a great job building out the ppt. @iamdeepaka if you want to add the market metrics that should finish the slides.

we can then try out some example queries using some of timescaleDBs functions for the live demo

**Comment by jfogerty18** [comment]
All sounds good. Deepak, after you add the market metrics slide, I will e-mail the slides to the professor.
